apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.imageData.name }}:{{ .Values.imageData.tag }}"
          ports:
            - containerPort: 8080
