apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    app: go-app
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  type: NodePort