name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'values.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Code
        run: build -o go-web-app

      - name: Test
        run: go test ./...

  static-code-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: 'v1.60'

  push-image:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}



    
