name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'values.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Code
        run: go build -o go-web-app

      - name: Test
        run: go test ./...

  static-code-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: 'v1.60'

  push-image:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}

  update-tag-values-yaml:
    runs-on: ubuntu-latest

    needs: push-image
    
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update values.yaml file
        run: 'sed -i "s/tag: [0-9]*/tag: ${{github.run_id}}/" k8s/manifests/go-web-app-helmchart/values.yaml'

      - name: Commit updated values.yaml file
        run: |
          git config --global user.email "souvik@example.com"
          git config --global user.name "Souvik Saha"
          git add k8s/manifests/go-web-app-helmchart/values.yaml
          git commit -m "Update tag in Helm chart"
          git push



    
